"""Generate `config/ontology.yaml` from the class list of a detector weight.

WHY THIS SCRIPT EXISTS

The ontology maps the detector's word for a thing onto a group and, where the detector's word reads
badly, onto a plainer word. It was maintained by hand, and it drifted: by 23 August 2026 it carried
roughly three hundred Open Images V7 entries the loaded weight could never emit, a `not_obstacles`
list written against that same absent vocabulary, and renames that made ordinary words vaguer.

A hand-maintained mapping of a machine-generated vocabulary will drift again. This script removes
that possibility by deriving the file from `model.names`, which is the only authority on what the
detector can actually say. Changing weights is then a regeneration rather than an edit.

WHAT IT EMITS

One bucket per detector class, named for the class. `ontology_class` therefore equals
`canonical_class` for every detection, which is the honest state of affairs: grouping changes no
behaviour except through `hazard`, and no group beyond `hazard` was ever read for anything but the
debug overlay and the telemetry counts.

An empty `hazard` bucket is emitted so the name exists for the mapper to read. Whether anything ever
enters it is deferred register item 5, the open decision on how a fall is detected.

THE TWO HAND-WRITTEN TABLES BELOW

`RENAMES` and `NOT_OBSTACLES` cannot come from the weight, because they are judgements about English
and about safety rather than facts about the vocabulary. Both are filtered against `model.names`
before they are written, so an entry for a class the weight cannot emit is dropped rather than
carried forward dormant. That filtering is what stops the drift this script was written to end.

USAGE

    python scripts/generate_ontology.py --model yolov8n.pt
    python scripts/generate_ontology.py --model yolov8n.pt --check
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
DEFAULT_OUT = REPO_ROOT / "config" / "ontology.yaml"

# Detector words that read badly when spoken aloud, mapped to the word used instead. Only wording is
# affected: the group and the stopping distance are unchanged. Kept deliberately short. A word that
# is already ordinary English is left alone, because renaming `vase` to "plant" and `laptop` to
# "computer" is what the previous file did and it lost information the listener could have used.
RENAMES = {
    "cell phone": "telephone",
    "dining table": "table",
    "refrigerator": "fridge",
    "tv": "television",
}

# Detector words whose detection is discarded before it becomes a fact. This is the only way for the
# walker to ignore something the camera saw, so an entry here costs an obstacle if it is wrong, and
# the list is held to a stricter standard than anything else in the file.
#
# `tie` is the sole entry. A necktie is worn by a person who is already detected as a person, so it
# contributes a duplicate object at the same distance and no obstacle of its own.
NOT_OBSTACLES = ["tie"]

HEADER = """\
# ============================================
# Safety ontology, generated from the detector weight
# ============================================
#
# DO NOT EDIT THIS FILE BY HAND. It is written by `scripts/generate_ontology.py` from the class list
# of the weight named below. Editing it here puts it out of step with the detector, which is the
# failure this generation replaced. To change the mapping, edit the tables in that script and
# regenerate. To change the vocabulary, regenerate against the new weight.
#
# WHAT THIS FILE IS FOR
#
# The detector produces one word for each thing it finds, chosen from a fixed list. This file may
# give that word a plainer replacement for the spoken description, and it puts the word in a group.
#
# WHAT THE GROUP CHANGES
#
# Only `hazard` changes what the walker does: anything in it makes the walker stop {hazard_m} m away
# rather than {stop_m} m. Every class below is in a group named after itself, so `ontology_class`
# equals `canonical_class` throughout and no grouping decision is being smuggled in. The names
# `hazard` and `unknown_obstacle` are read by the code and must not be renamed. `unknown_obstacle`
# has no bucket because it is the mapper's fallback for a word it does not recognise.
#
# `hazard` IS EMPTY AND THEREFORE UNREACHABLE
#
# No word from this vocabulary is in it, so the hazard stopping distance is never applied. Stairs,
# ramps, drop-offs and wet floors are invisible to a detector that has no word for them. This is an
# open decision rather than an oversight: how a fall is detected is item 5 of the deferred register,
# and is settled from laboratory captures. See `thesis/Claude Session/LAB_SESSION_CHECKLIST.md`.
#
# HOW A WORD IS MATCHED
#
# The detector's word is lowercased and looked up in `not_obstacles` first, and a match there ends
# it: the detection is discarded before it becomes a fact. Otherwise the word is looked up in
# `synonyms_to_canonical`, then in the `canonical` lists. Anything unmatched becomes
# `unknown_obstacle`. The match is exact. When it was approximate, a stop sign matched a staircase
# and was treated as a fall hazard, and a necktie matched a person.
#
# ---------------------------------------------------------------------------------------------
# Weight:  {weight}
# Classes: {count}
# ---------------------------------------------------------------------------------------------
"""


def build_document(weight_name: str, names: list[str], hazard_m: str, stop_m: str) -> str:
    """Return the full text of the ontology file for the given class list."""
    present = {n.lower() for n in names}
    renames = {k: v for k, v in RENAMES.items() if k in present}
    not_obstacles = [w for w in NOT_OBSTACLES if w in present]

    lines = [HEADER.format(weight=weight_name, count=len(names),
                           hazard_m=hazard_m, stop_m=stop_m)]

    lines.append("ontology:")
    lines.append("  # Empty by decision, not by omission. See the header.")
    lines.append("  - name: hazard")
    lines.append("    canonical: []")
    lines.append("")
    for raw in names:
        # A dropped class is never mapped, because `is_not_obstacle` is consulted first. Emitting a
        # bucket for one would be configuration that can never fire.
        if raw.lower() in not_obstacles:
            continue
        canonical = renames.get(raw.lower(), raw.lower())
        lines.append(f"  - name: {canonical}")
        lines.append(f"    canonical: [{canonical}]")
    lines.append("")

    lines.append("# Detector words routed to a different spoken word. Wording only.")
    lines.append("synonyms_to_canonical:")
    if renames:
        for raw, canonical in sorted(renames.items()):
            lines.append(f"  {raw}: {canonical}")
    else:
        lines.append("  {}")
    lines.append("")

    lines.append("# Detections discarded before they become facts. See the script's comment.")
    lines.append("not_obstacles:")
    if not_obstacles:
        for word in not_obstacles:
            lines.append(f"  - {word}")
    else:
        lines.append("  []")
    lines.append("")

    return "\n".join(lines)


def class_names(model_path: str) -> list[str]:
    """Read the ordered class list from a detector weight."""
    from ultralytics import YOLO

    model = YOLO(model_path)
    names = model.names
    return [str(names[i]) for i in sorted(names)]


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--model", default="yolov8n.pt",
                        help="detector weight to read the class list from")
    parser.add_argument("--out", default=str(DEFAULT_OUT),
                        help="path to write")
    parser.add_argument("--check", action="store_true",
                        help="exit non-zero if the file on disk differs from what would be written")
    parser.add_argument("--hazard-stop-m", default="2.00")
    parser.add_argument("--object-stop-m", default="0.70")
    args = parser.parse_args(argv)

    names = class_names(args.model)
    document = build_document(Path(args.model).name, names,
                              args.hazard_stop_m, args.object_stop_m)
    out = Path(args.out)

    if args.check:
        current = out.read_text(encoding="utf-8") if out.exists() else ""
        if current != document:
            print(f"{out} is out of step with {args.model}. Regenerate it.", file=sys.stderr)
            return 1
        print(f"{out} matches {args.model}, {len(names)} classes.")
        return 0

    out.write_text(document, encoding="utf-8")
    print(f"Wrote {out}: {len(names)} classes from {args.model}.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
